### ISSUE TITLE
training slow

### ISSUE THREAD

**Issue by loscheris** [DetectionTeamUCAS/RRPN_Faster-RCNN_Tensorflow#12]
Hi, I found the training is extremely slow, it took about 2 mins to finish one step (since batch size is 1, I assumed for every step only one image is trained). All images have size about 800*1000 after reshaping. I run the code on K80 GPU and the trianing process only occupies 72MB GPU memory. I'm wondering if there's any problem in my environment. Thanks

**Comment by yangxue0827** [comment]
Mainly slow in iou's calculations and nms processing, you can replace it by implementing a more efficient calculation method yourself. Or you can use this [code](https://github.com/yangxue0827/R2CNN_FPN_Tensorflow). @loscheris

**Comment by loscheris** [comment]
Thanks! @yangxue0827 , I will have a try R2CNN later!

Btw, Is this a normal training speed in RRPN? What's your training speed in RRPN?

**Comment by yangxue0827** [comment]
Not normal, you may set wrong gpu index. Please check the default gpu in cfgs.py, and set right index according to your environment. @loscheris

**Comment by DianaZhang** [comment]
Hi, I have the same problem. When I use train. py, a step takes about 5 minutes, and I have two gpUs, but only one GPU is called. I modified cfgs.py, line 15 with GPU_GROUP = 0,1, but it was of no use. I don't know what to do next.
