### ISSUE TITLE
Some questions!!

### ISSUE THREAD

**Issue by tsing-cv** [DetectionTeamUCAS/RRPN_Faster-RCNN_Tensorflow#14]
1. the performmence of rrpn_faster-rcnn and rrpn fpn? which obtains better result.
2. defined function in .cu: overlaps_kernel and rotate_nms_kernel, can you give more annotations for them.
3. how to allocate threshold, what is  the principle
```python
            threshold = {'roundabout': 0.1, 'tennis-court': 0.3, 'swimming-pool': 0.1, 'storage-tank': 0.2,
                         'soccer-ball-field': 0.3, 'small-vehicle': 0.2, 'ship': 0.05, 'plane': 0.3,
                         'large-vehicle': 0.1, 'helicopter': 0.2, 'harbor': 0.0001, 'ground-track-field': 0.3,
                         'bridge': 0.0001, 'basketball-court': 0.3, 'baseball-diamond': 0.3}
``` 
4. if I dont want to use PRETRAINED model, I just what to train for zero. what should I do?
@yangxue0827

**Comment by yangxue0827** [comment]
1、rrpn fpn的的fpn部分有问题，所以不建议使用那个代码;
2、计算旋转iou的代码可以参考rrpn的文章，以及[知乎的讨论](https://www.zhihu.com/question/28854765?sort=created)
3、阈值是调参的，知识经验设置
4、不想用与训练权重的话，在train.py里吧加载模型的代码注释就行。

**Comment by tsing-cv** [comment]
@yangxue0827 非常感谢你。
