### ISSUE TITLE
训练中损失已经很低，但模型预测很差

### ISSUE THREAD

**Issue by guoguangchao** [DetectionTeamUCAS/RRPN_Faster-RCNN_Tensorflow#16]
训练身份证检测的四个类别，包括name、address、id_num、head，训练了4万步左右，使用训练的模型预测的结果如下：
![1](https://user-images.githubusercontent.com/5878481/49660548-cf460d80-fa81-11e8-9d0d-def8c6576a2b.jpg)

![3](https://user-images.githubusercontent.com/5878481/49660198-f9e39680-fa80-11e8-8e13-6b47db96151c.jpg)

tensorboard的输出如下：

![loss1](https://user-images.githubusercontent.com/5878481/49660144-e0424f00-fa80-11e8-8271-b2709c4e1aa4.png)
![loss2](https://user-images.githubusercontent.com/5878481/49660157-ea644d80-fa80-11e8-8f23-cce40f85c409.png)
![acc](https://user-images.githubusercontent.com/5878481/49660170-f0f2c500-fa80-11e8-8f91-021a4244e75c.png)
![normal](https://user-images.githubusercontent.com/5878481/49660240-0ec02a00-fa81-11e8-8eb5-cd401d6acd48.jpg)
![default](https://user-images.githubusercontent.com/5878481/49660290-28fa0800-fa81-11e8-8a6f-d07630884091.jpg)
请问：
1、tensorboard中的损失已经比较低，而且tensorboard image标签下的图片anchor和ios也正常，为什么预测会差这么多呢？
2、上面最后一张图tensorboard image标签中，发现有的步中image出现了花屏的情况，但我查看训练数据中的图片都是正常的，这个可能是什么原因呢？
谢谢！

**Comment by tsing-cv** [comment]
你的数据量多大呢？

**Comment by guoguangchao** [comment]
3000多张

**Comment by guoguangchao** [comment]
谢谢，我把w和h交换一下试试

**Comment by guoguangchao** [comment]
我将w和h调换后可视化中没有花屏的问题了，训练了14万步左右，但预测还是很差，是训练的步数不够吗？
训练输出的损失如下：
```
2018-12-12 05:47:21: step142820    image_name:001133.jpg |	
                                                    rpn_loc_loss:0.0595558062196 |	 rpn_cla_loss:0.00367080210708 |	
                                                    rpn_total_loss:0.0632266104221 |
                                                    fast_rcnn_loc_loss:0.133372455835 |	 fast_rcnn_cla_loss:0.0368532128632 |	
                                                    fast_rcnn_total_loss:0.170225664973 |	
                                                    total_loss:0.561481237411 |	 pre_cost_time:0.216724872589s
```
预测的结果如下：
![000019_r](https://user-images.githubusercontent.com/5878481/49865942-4fe37180-fdd4-11e8-8153-f1fff1e7284b.jpg)
![000026_r](https://user-images.githubusercontent.com/5878481/49865971-625dab00-fdd4-11e8-9ee6-4896d8af81ef.jpg)
![000070_r](https://user-images.githubusercontent.com/5878481/49865987-70abc700-fdd4-11e8-9e85-144fe023f910.jpg)
配置文件中我修改了anchor的相关配置：
ANCHOR_SCALES = [0.125, 0.25, 0.5, 1., 2.0]  # [4, 8, 16, 32]
ANCHOR_RATIOS = [1, 1 / 2, 2., 1 / 3., 3., 5.,  4., 6.]
请问，这个可能是什么原因导致的呢，谢谢！！

**Comment by yangxue0827** [comment]
个人觉得你这个任务只用检测解决是有问题的，大多数类是要靠内容才能区分出来了。 @guoguangchao

**Comment by guoguangchao** [comment]
谢谢，我之前用faster rcnn训练过没有旋转角度的身份证，效果还不错的，我再看下有没有解决方法，感谢您的回复！

**Comment by yangxue0827** [comment]
那可能是这个代码不太适合你这个任务吧 @guoguangchao

**Comment by guoguangchao** [comment]
估计是我哪里弄错了，从这个代码中学到很多，感谢分享！

**Comment by u101022205** [comment]
> 估计是我哪里弄错了，从这个代码中学到很多，感谢分享！

@guoguangchao
想請問你最後有找到原因嗎？

**Comment by guoguangchao** [comment]
> > 估计是我哪里弄错了，从这个代码中学到很多，感谢分享！
> 
> @guoguangchao
> 想請問你最後有找到原因嗎？

还没有。。

**Comment by xieyufei1993** [comment]
你好，有些问题想向你请教，方便留个邮箱吗？
@guoguangchao

**Comment by zhoujinhai** [comment]
> 估计是我哪里弄错了，从这个代码中学到很多，感谢分享！

请问一下后面解决斜框问题了吗
