### ISSUE TITLE
旋转矩形iou的计算

### ISSUE THREAD

**Issue by WeichengDDD** [DetectionTeamUCAS/RRPN_Faster-RCNN_Tensorflow#2]
cv2.rotatedRectangleIntersection得不到正确的交点坐标，会影响最后iou计算。
boxes1 = [ [200,200,100,100, -45]]， boxes2 = [[150,150,100,100, -45], [250,250,100,100, -45]]
cv2.rotatedRectangleIntersection方法分别返回4个交点和3个交点。

**Comment by yangxue0827** [comment]
谢谢提醒
