### ISSUE TITLE
ValueError: Variable resnet_v1_101/block3/unit_1/bottleneck_v1/shortcut/weights/Momentum/ does not exist, or was not created with tf.get_variable(). Did you mean to set reuse=None in VarScope?Ð

### ISSUE THREAD

**Issue by DianaZhang** [DetectionTeamUCAS/RRPN_Faster-RCNN_Tensorflow#36]
在我运行multi_gpu_train.py的时候，在optimizer.apply_gradients(grads, global_step)这一步遇到了这个问题，求助大神又没有遇到过，要怎么解决。

**Comment by yangxue0827** [comment]
参考这个https://github.com/DetectionTeamUCAS/FPN_Tensorflow/blob/master/tools/multi_gpu_train.py  这个repo的多gpu我没写好 @DianaZhang

**Comment by DianaZhang** [comment]
已收到邮件，感谢您的回复与建议。-------- 原始邮件 --------主题：Re: [DetectionTeamUCAS/RRPN_Faster-RCNN_Tensorflow] ValueError: Variable resnet_v1_101/block3/unit_1/bottleneck_v1/shortcut/weights/Momentum/ does not exist, or was not created with tf.get_variable(). Did you mean to set reuse=None in VarScope?Ð (#36)发件人：yangxue 收件人：DetectionTeamUCAS/RRPN_Faster-RCNN_Tensorflow 抄送：Diana ,Mention 参考这个https://github.com/DetectionTeamUCAS/FPN_Tensorflow/blob/master/tools/multi_gpu_train.py  这个repo的多gpu我没写好 @DianaZhang



—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or mute the thread.

[

{

"@context": "http://schema.org",

"@type": "EmailMessage",

"potentialAction": {

"@type": "ViewAction",

"target": "https://github.com/DetectionTeamUCAS/RRPN_Faster-RCNN_Tensorflow/issues/36?email_source=notifications\u0026email_token=AHLP37RHB7LEP4KTF7AC7I3PW6SXHA5CNFSM4HPM64DKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGODWERY2A#issuecomment-495524968",

"url": "https://github.com/DetectionTeamUCAS/RRPN_Faster-RCNN_Tensorflow/issues/36?email_source=notifications\u0026email_token=AHLP37RHB7LEP4KTF7AC7I3PW6SXHA5CNFSM4HPM64DKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGODWERY2A#issuecomment-495524968",

"name": "View Issue"

},

"description": "View this Issue on GitHub",

"publisher": {

"@type": "Organization",

"name": "GitHub",

"url": "https://github.com"

}

}

]
