### ISSUE TITLE
question about train

### ISSUE THREAD

**Issue by nuist-xinyu** [DetectionTeamUCAS/RRPN_Faster-RCNN_Tensorflow#41]
ain.py 
++--++--++--++--++--++--++--++--++--++--++--++--++--++--++--++--++--++--++--++--
/home/xinyu/RRPN_Faster-RCNN_Tensorflow-master
WARNING: Logging before flag parsing goes to stderr.
W0822 20:20:16.743671 140499026802432 deprecation_wrapper.py:119] From ../libs/networks/mobilenet/mobilenet.py:356: The name tf.nn.avg_pool is deprecated. Please use tf.nn.avg_pool2d instead.

tfrecord path is --> /home/xinyu/RRPN_Faster-RCNN_Tensorflow-master/data/tfrecord/VOCdevkit_train*
W0822 20:20:16.779687 140499026802432 deprecation_wrapper.py:119] From ../data/io/read_tfrecord.py:85: The name tf.train.match_filenames_once is deprecated. Please use tf.io.match_filenames_once instead.

W0822 20:20:16.782697 140499026802432 deprecation.py:323] From ../data/io/read_tfrecord.py:87: string_input_producer (from tensorflow.python.training.input) is deprecated and will be removed in a future version.
Instructions for updating:
Queue-based input pipelines have been replaced by `tf.data`. Use `tf.data.Dataset.from_tensor_slices(string_tensor).shuffle(tf.shape(input_tensor, out_type=tf.int64)[0]).repeat(num_epochs)`. If `shuffle=False`, omit the `.shuffle(...)`.
W0822 20:20:16.785707 140499026802432 deprecation.py:323] From /home/xinyu/anaconda3/envs/RRPN/lib/python2.7/site-packages/tensorflow/python/training/input.py:278: input_producer (from tensorflow.python.training.input) is deprecated and will be removed in a future version.
Instructions for updating:
Queue-based input pipelines have been replaced by `tf.data`. Use `tf.data.Dataset.from_tensor_slices(input_tensor).shuffle(tf.shape(input_tensor, out_type=tf.int64)[0]).repeat(num_epochs)`. If `shuffle=False`, omit the `.shuffle(...)`.
W0822 20:20:16.786247 140499026802432 deprecation.py:323] From /home/xinyu/anaconda3/envs/RRPN/lib/python2.7/site-packages/tensorflow/python/training/input.py:190: limit_epochs (from tensorflow.python.training.input) is deprecated and will be removed in a future version.
Instructions for updating:
Queue-based input pipelines have been replaced by `tf.data`. Use `tf.data.Dataset.from_tensors(tensor).repeat(num_epochs)`.
W0822 20:20:16.787324 140499026802432 deprecation.py:323] From /home/xinyu/anaconda3/envs/RRPN/lib/python2.7/site-packages/tensorflow/python/training/input.py:199: __init__ (from tensorflow.python.training.queue_runner_impl) is deprecated and will be removed in a future version.
Instructions for updating:
To construct input pipelines, use the `tf.data` module.
W0822 20:20:16.788012 140499026802432 deprecation.py:323] From /home/xinyu/anaconda3/envs/RRPN/lib/python2.7/site-packages/tensorflow/python/training/input.py:199: add_queue_runner (from tensorflow.python.training.queue_runner_impl) is deprecated and will be removed in a future version.
Instructions for updating:
To construct input pipelines, use the `tf.data` module.
W0822 20:20:16.790565 140499026802432 deprecation.py:323] From ../data/io/read_tfrecord.py:19: __init__ (from tensorflow.python.ops.io_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Queue-based input pipelines have been replaced by `tf.data`. Use `tf.data.TFRecordDataset`.
W0822 20:20:16.791338 140499026802432 deprecation_wrapper.py:119] From ../data/io/read_tfrecord.py:22: The name tf.parse_single_example is deprecated. Please use tf.io.parse_single_example instead.

W0822 20:20:16.791433 140499026802432 deprecation_wrapper.py:119] From ../data/io/read_tfrecord.py:25: The name tf.FixedLenFeature is deprecated. Please use tf.io.FixedLenFeature instead.

W0822 20:20:16.816281 140499026802432 deprecation_wrapper.py:119] From ../data/io/image_preprocess.py:25: The name tf.image.resize_bilinear is deprecated. Please use tf.compat.v1.image.resize_bilinear instead.

W0822 20:20:16.875123 140499026802432 deprecation_wrapper.py:119] From ../data/io/image_preprocess.py:64: The name tf.random_uniform is deprecated. Please use tf.random.uniform instead.

W0822 20:20:16.905863 140499026802432 deprecation.py:323] From ../data/io/read_tfrecord.py:97: batch (from tensorflow.python.training.input) is deprecated and will be removed in a future version.
Instructions for updating:
Queue-based input pipelines have been replaced by `tf.data`. Use `tf.data.Dataset.batch(batch_size)` (or `padded_batch(...)` if `dynamic_pad=True`).
W0822 20:20:16.912734 140499026802432 deprecation.py:323] From train.py:36: py_func (from tensorflow.python.ops.script_ops) is deprecated and will be removed in a future version.
Instructions for updating:
tf.py_func is deprecated in TF V2. Instead, there are two
    options available in V2.
    - tf.py_function takes a python function which manipulates tf eager
    tensors instead of numpy arrays. It's easy to convert a tf eager tensor to
    an ndarray (just call tensor.numpy()) but having access to eager tensors
    means `tf.py_function`s can use accelerators such as GPUs as well as
    being differentiable using a gradient tape.
    - tf.numpy_function maintains the semantics of the deprecated tf.py_func
    (it is not differentiable, and manipulates numpy arrays). It drops the
    stateful argument making all functions stateful.
    
W0822 20:20:16.921506 140499026802432 deprecation_wrapper.py:119] From train.py:44: The name tf.no_regularizer is deprecated. Please use tf.compat.v1.no_regularizer instead.

W0822 20:20:16.923095 140499026802432 deprecation_wrapper.py:119] From ../libs/networks/resnet.py:28: The name tf.GraphKeys is deprecated. Please use tf.compat.v1.GraphKeys instead.

Traceback (most recent call last):
  File "train.py", line 195, in <module>
    train()
  File "train.py", line 55, in train
    gtboxes_batch=gtboxes_and_label)
  File "../libs/networks/build_whole_network.py", line 357, in build_whole_detection_network
    is_training=self.is_training)
  File "../libs/detection_oprations/proposal_opr.py", line 66, in postprocess_rpn_proposals
    use_gpu=True)
  File "../libs/box_utils/nms_rotate.py", line 31, in nms_rotate
    device_id=gpu_id)
  File "../libs/box_utils/nms_rotate.py", line 101, in nms_rotate_gpu
    Tout=tf.int64)
  File "/home/xinyu/anaconda3/envs/RRPN/lib/python2.7/site-packages/tensorflow/python/util/deprecation.py", line 324, in new_func
    return func(*args, **kwargs)
  File "/home/xinyu/anaconda3/envs/RRPN/lib/python2.7/site-packages/tensorflow/python/ops/script_ops.py", line 480, in py_func
    return py_func_common(func, inp, Tout, stateful, name=name)
  File "/home/xinyu/anaconda3/envs/RRPN/lib/python2.7/site-packages/tensorflow/python/ops/script_ops.py", line 462, in py_func_common
    func=func, inp=inp, Tout=Tout, stateful=stateful, eager=False, name=name)
  File "/home/xinyu/anaconda3/envs/RRPN/lib/python2.7/site-packages/tensorflow/python/ops/script_ops.py", line 257, in _internal_py_func
    token = _py_funcs.insert(func)
  File "/home/xinyu/anaconda3/envs/RRPN/lib/python2.7/site-packages/tensorflow/python/ops/script_ops.py", line 144, in insert
    self._funcs[token] = func
  File "/home/xinyu/anaconda3/envs/RRPN/lib/python2.7/weakref.py", line 118, in __setitem__
    self.data[key] = KeyedRef(value, self._remove, key)
  File "/home/xinyu/anaconda3/envs/RRPN/lib/python2.7/weakref.py", line 311, in __new__
    self = ref.__new__(type, ob, callback)
TypeError: cannot create weak reference to 'builtin_function_or_method' object

**Comment by liyinhua4346** [comment]
请问你们是训练了多长时间，我都训练几天了，loss还是挺高的

**Comment by nuist-xinyu** [comment]
这个要看数据集把 我们数据集比较大 训练了三天左右 
loss高的话  你提把你损失权重调小一点试试




------------------ 原始邮件 ------------------
发件人: "liyinhua4346"<notifications@github.com>; 
发送时间: 2019年9月5日(星期四) 中午11:54
收件人: "DetectionTeamUCAS/RRPN_Faster-RCNN_Tensorflow"<RRPN_Faster-RCNN_Tensorflow@noreply.github.com>; 
抄送: "请叫我辛先生"<626673305@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [DetectionTeamUCAS/RRPN_Faster-RCNN_Tensorflow] question abouttrain (#41)



请问你们是训练了多长时间，我都训练几天了，loss还是挺高的

**Comment by morning4346** [comment]
我使用eval做测试时，P-R曲线到了一个阶段急剧下降，请问你知道怎么回事吗，也就是测试结果是召回率很高，但是Precision很低，

**Comment by morning4346** [comment]
您知道为什么我的结果显示的PR曲线中，到了一定阶段，precsion急剧下降原因是什么吗



---Original---

**Comment by happydayhappyday** [comment]
> 您知道为什么我的结果显示的PR曲线中，到了一定阶段，precsion急剧下降原因是什么吗
> […](#)
> ---Original--- From: "nuist-xinyu"<notifications@github.com&gt; Date: Mon, Sep 9, 2019 09:16 AM To: "DetectionTeamUCAS/RRPN_Faster-RCNN_Tensorflow"<RRPN_Faster-RCNN_Tensorflow@noreply.github.com&gt;; Cc: "Comment"<comment@noreply.github.com&gt;;"morning4346"<2995235418@qq.com&gt;; Subject: Re: [DetectionTeamUCAS/RRPN_Faster-RCNN_Tensorflow] question about train (#41) 这个要看数据集把 我们数据集比较大 训练了三天左右 loss高的话 你提把你损失权重调小一点试试
> ------------------ 原始邮件 ------------------ 发件人: "liyinhua4346"<notifications@github.com&gt;; 发送时间: 2019年9月5日(星期四) 中午11:54 收件人: "DetectionTeamUCAS/RRPN_Faster-RCNN_Tensorflow"<RRPN_Faster-RCNN_Tensorflow@noreply.github.com&gt;; 抄送: "请叫我辛先生"<626673305@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 主题: Re: [DetectionTeamUCAS/RRPN_Faster-RCNN_Tensorflow] question abouttrain (#41) 请问你们是训练了多长时间，我都训练几天了，loss还是挺高的 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or mute the thread. — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or mute the thread.

请问你训练出来了吗？我现在遇到一个问题，训练了很久loss都很高，请问你有什么解决办法吗？或者有什么建议，谢谢

**Comment by FortuneStar** [comment]
> 请问你们是训练了多长时间，我都训练几天了，loss还是挺高的

你好，请问您的问题解决了吗？我训练的loss值也很高，中间停止训练，测试了一下，效果很差。

**Comment by nuist-xinyu** [comment]
不好意思啊&nbsp; 我已经不做这个了 时间过去的太久了 我也记不得了




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "FortuneStar"<notifications@github.com&gt;; 
发送时间: 2020年4月17日(星期五) 上午9:16
收件人: "DetectionTeamUCAS/RRPN_Faster-RCNN_Tensorflow"<RRPN_Faster-RCNN_Tensorflow@noreply.github.com&gt;; 
抄送: "请叫我辛先生"<626673305@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [DetectionTeamUCAS/RRPN_Faster-RCNN_Tensorflow] question about train (#41)



请问你们是训练了多长时间，我都训练几天了，loss还是挺高的
  你好，请问您的问题解决了吗？我训练的loss值也很高，中间停止训练，测试了一下，效果很差。

**Comment by yangxue0827** [comment]
这个repo很久了，建议使用我其他新的repo，效果好速度快 @FortuneStar

**Comment by FortuneStar** [comment]
> 这个repo很久了，建议使用我其他新的repo，效果好速度快 @FortuneStar

您指的是R2CNN_Faster_RCNN_Tensorflow这个模型是吗？

**Comment by yangxue0827** [comment]
RetinatNet_Tensorflow_Rotation    R3Det_Tensorflow也可以 @FortuneStar

**Comment by FortuneStar** [comment]
> RetinatNet_Tensorflow_Rotation R3Det_Tensorflow也可以 @FortuneStar

好的，谢谢您，我有个问题请教您，我自己标记的样本是用labelme工具，生成的是任意四边形，不知道您用的是什么工具。

**Comment by yangxue0827** [comment]
我用的开源数据集，DOTA也是任意四边形的标注，代码里会转成旋转矩形 @FortuneStar

**Comment by FortuneStar** [comment]
> 我用的开源数据集，DOTA也是任意四边形的标注，代码里会转成旋转矩形 @FortuneStar

好的，谢谢您的解答
