### ISSUE TITLE
OutOfRangeError (see above for traceback): PaddingFIFOQueue '_2_get_batch/batch/padding_fifo_queue'

### ISSUE THREAD

**Issue by yhyaaln** [DetectionTeamUCAS/RRPN_Faster-RCNN_Tensorflow#44]
I used my own data, and made tfrecord sucessfully.
But it had an error when I want to train.
How can I solution? Thanks.

OutOfRangeError (see above for traceback): PaddingFIFOQueue '_2_get_batch/batch/padding_fifo_queue' is closed and has insufficient elements (requested 1, current size 0)
         [[Node: get_batch/batch = QueueDequeueManyV2[component_types=[DT_STRING, DT_FLOAT, DT_INT32, DT_INT32], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](get_batch/batch/padding_fifo_queue, get_batch/batch/n)]]

**Comment by bonnie-cbw** [comment]
Same problem. Have you solved it? Thank you so much for your help!!!
