### ISSUE TITLE
关于Dota数据集的提问？

### ISSUE THREAD

**Issue by FortuneStar** [DetectionTeamUCAS/RRPN_Faster-RCNN_Tensorflow#49]
小白第一次使用这个数据集，不是很熟悉，有两个疑问？
1.训练数据集中的labelTxt-v1.5和lTxt-v1.0有什么关系吗？
2.Train_Task2_gt.zip和labeltxt.zip是什么关系？

**Comment by yangxue0827** [comment]
DOTA数据集分两个版本，分别是1.5和1.0，1他们的图片是一样的，区别在于1.5版本多了一类且给了像素小于10一下的目标标注。

DOTA又分水平旋转两个检测任务，所以有两种标注。

**Comment by FortuneStar** [comment]
嗷嗷，多谢仓主的回答。
