### ISSUE TITLE
inference.py, eval.py, demo.py all buggy!

### ISSUE THREAD

**Issue by vinjohn** [DetectionTeamUCAS/RRPN_Faster-RCNN_Tensorflow#5]
Hi, the inference.py, eval.py and demo.py are all buggy in this repo, would you please update a version which can really work?
The train.py is fine.

**Comment by yangxue0827** [comment]
can you give me the error information. @vinjohn

**Comment by vinjohn** [comment]
for R2CNN, everything is fine.
for RRPN, take inference.py for instance:

the build_whole_detection_network need 3 input and return 6 output.

det_net.build_whole_detection_network(input_img_batch=img_batch, gtboxes_h_batch=None, gtboxes_r_batch=None)

however, the implementation of build_whole_detection_network in libs/networks/build_whole_network.py:

build_whole_detection_network(self, input_img_batch, gtboxes_batch)
2 input and 4 return (final_boxes, final_scores, final_category, loss_dict)

the exact error message I get is:
TypeError: build_whole_detection_network() got an unexpected keyword argument 'gtboxes_h_batch'

**Comment by vinjohn** [comment]
This time the inference is going well, but I think a nms process should be added, anyway, I add it myself.

The anchor scale question, please help, thanks a million!

**Comment by yangxue0827** [comment]
base anchor * anchor scales = [16, 32, 64, 128, 256, 512] as the base_anchor_size_list. Anchor ratios = [1, ... ,1/7] controls the shape of the anchor under the same base. roi_scale_factors controls  the value of predict offset in a small range. @vinjohn
