### ISSUE TITLE
关于角度的计算

### ISSUE THREAD

**Issue by FortuneStar** [DetectionTeamUCAS/RRPN_Faster-RCNN_Tensorflow#53]
请问下，代码中的角度和OpenCV里面的角度定义是一致的吗？OpenCV里面水平的物体，角度是-90度，竖起来角度还是-90度

**Comment by yangxue0827** [comment]
采用的就是opencv的定义方式，角度范围[-90,0) @FortuneStar

**Comment by FortuneStar** [comment]
> 采用的就是opencv的定义方式，角度范围[-90,0) @FortuneStar

是这样的，我发现您推荐的几个模型都存在一种情况就是，当训练了一个模型后，检测图片中的物体是水平的但是，目标框却会旋转45度，即使用训练过的样本测试还是会出现这种情况，旋转检测模型始终没有两点定位模型准确，所以我对OpenCV里面关于旋转矩形的角度有了疑问

**Comment by yangxue0827** [comment]
给一个图例 @FortuneStar

**Comment by FortuneStar** [comment]
> 给一个图例 @FortuneStar

![001](https://user-images.githubusercontent.com/49903328/81045285-7da8e900-8ee8-11ea-842c-639f19d8c1d7.jpg)
![002](https://user-images.githubusercontent.com/49903328/81045294-80a3d980-8ee8-11ea-8dae-1879034a0762.jpg)
您看下，这种情况的样本还有好几个，我不清楚，同样的角度的火车票，为什么检测结果会差别这么多，OpenCV里面关于旋转矩形的角度，以及宽高的定义有别于通常中的理解，你帮忙分析下。

**Comment by yangxue0827** [comment]
这个是边界问题，详细分析可以看SCRDet，SCRdet++，CSL论文，论文下载链接见https://yangxue0827.github.io/ @FortuneStar

**Comment by FortuneStar** [comment]
> SCRDet
好的，谢谢，我看下，我想问下您说的边界问题，在代码中可以解决吗，还是说需要新的模型才能解决这个问题，另外我在知乎看到了您对SCRDet的介绍，先谢谢啦。

**Comment by FortuneStar** [comment]
> 这个是边界问题，详细分析可以看SCRDet，SCRdet++，CSL论文，论文下载链接见https://yangxue0827.github.io/ @FortuneStar

好的，谢谢，我看下，我想问下您说的边界问题，在代码中可以解决吗，还是说需要新的模型才能解决这个问题，另外我在知乎看到了您对SCRDet的介绍，先谢谢啦。

**Comment by yangxue0827** [comment]
使用iou smooth l1 loss应该可以较好解决 @FortuneStar

**Comment by FortuneStar** [comment]
> 使用iou smooth l1 loss应该可以较好解决 @FortuneStar

我使用的您提供的R2CNN_Rotate，也存在这个问题，那就是需要使用新的模型（SCRDet）才可以规避掉这个问题是吗

**Comment by yangxue0827** [comment]
建议你使用retinanet_tensorflow_rotation或者r3det这两个代码，里面都集成了iou smooth l1 loss @FortuneStar

**Comment by FortuneStar** [comment]
> 建议你使用retinanet_tensorflow_rotation或者r3det这两个代码，里面都集成了iou smooth l1 loss @FortuneStar

好的，谢谢您的耐心回答。
