### ISSUE TITLE
train

### ISSUE THREAD

**Issue by Starsasa** [DetectionTeamUCAS/RRPN_Faster-RCNN_Tensorflow#7]
您好，根据您的步骤重新训练了一遍，可是最终map只有百分之八，想请教您，这中间环节哪可能出错导致这个结果。训练步骤如下：对训练数据先进行train_crop.py,然后convert_data_to_tfrecord.py，最后train.py

**Comment by yangxue0827** [comment]
检测一下数据处理代码。
